apiVersion: devopsinfra.cps-managedpools.m.crossplane.io/v1alpha1
kind: ManagedDevOpsPool
metadata:
  annotations:
    meta.upbound.io/example-id: devopsinfra/v1alpha1/manageddevopspool
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    azureDevopsOrganization:
    - organization:
      - parallelism: 1
        url: https://dev.azure.com/example
    devCenterProjectId: ${azurerm_dev_center_project.example.id}
    location: ${azurerm_resource_group.example.location}
    maximumConcurrency: 1
    resourceGroupName: ${azurerm_resource_group.example.name}
    statelessAgent:
    - {}
    virtualMachineScaleSetFabric:
    - image:
      - wellKnownImageName: ubuntu-24.04/buffer
      skuName: Standard_D2ads_v5
