apiVersion: manageddevopspool.azurerm.crossplane.io/v1alpha1
kind: Pool
metadata:
  name: example-managed-devops-pool
spec:
  forProvider:
    name: example-manageddevopspools
    resourceGroupName: example-resources
    location: West Europe
    devCenterProjectId: /subscriptions/<SUBSCRIPTION_ID>/resourceGroups/example-resources/providers/Microsoft.DevCenter/projects/example
    maximumConcurrency: 1
    azureDevopsOrganization:
      - organization:
          - url: https://dev.azure.com/example
            parallelism: 1
    virtualMachineScaleSetFabric:
      - skuName: Standard_D2ads_v5
        image:
          - wellKnownImageName: ubuntu-24.04/latest
    statelessAgent:
      - {}
  providerConfigRef:
    name: default


apiVersion: azure.m.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: manageddevopspool/v1alpha1/pool
  labels:
    testing.upbound.io/example-name: example
  name: example-resources
spec:
  forProvider:
    location: West Europe
  providerConfigRef:
    name: default

