name: hashicorp/azurerm
resources:
    azurerm_managed_devops_pool:
        subCategory: "DevOps Infrastructure"
        description: Manages a Managed DevOps Pool.
        name: azurerm_managed_devops_pool
        title: azurerm_managed_devops_pool Resource
        examples:
            - name: example
              manifest: |
                resource "azurerm_resource_group" "example" {
                  name     = "example-resources"
                  location = "West Europe"
                }

                resource "azurerm_dev_center" "example" {
                  name                = "example-devcenter"
                  resource_group_name = azurerm_resource_group.example.name
                  location            = azurerm_resource_group.example.location
                }

                resource "azurerm_dev_center_project" "example" {
                  dev_center_id       = azurerm_dev_center.example.id
                  location            = azurerm_resource_group.example.location
                  name                = "example"
                  resource_group_name = azurerm_resource_group.example.name
                }

                resource "azurerm_managed_devops_pool" "example" {
                  name                  = "example-manageddevopspools"
                  resource_group_name   = azurerm_resource_group.example.name
                  location              = azurerm_resource_group.example.location
                  dev_center_project_id = azurerm_dev_center_project.example.id
                  maximum_concurrency   = 1

                  azure_devops_organization {
                    organization {
                      parallelism = 1
                      url         = "https://dev.azure.com/example"
                    }
                  }

                  stateless_agent {}

                  virtual_machine_scale_set_fabric {
                    sku_name = "Standard_D2ads_v5"

                    image {
                      well_known_image_name = "ubuntu-24.04/buffer"
                    }
                  }
                }
        argumentDocs:
            dev_center_project_id: (Required) The ID of the Dev Center project.
            location: (Required) The Azure Region where the Managed DevOps Pool should exist.
            maximum_concurrency: (Required) Defines how many resources can there be created at any given time.
            name: (Required) The name which should be used for this Managed DevOps Pool.
            resource_group_name: (Required) The name of the Resource Group where the Managed DevOps Pool should exist.
            azure_devops_organization: (Required) An azure_devops_organization block as defined below.
            identity: (Optional) An identity block as defined below.
            stateful_agent: (Optional) A stateful_agent block as defined below.
            stateless_agent: (Optional) A stateless_agent block as defined below.
            tags: (Optional) A mapping of tags which should be assigned to the Managed DevOps Pool.
            work_folder: (Optional) Specifies the work folder for every agent in the pool.
            id: (String) The ID of the Managed DevOps Pool.
        importStatements: []
